#!/bin/bash
# build-codec2.sh — build codec2.xcframework from a pinned upstream version.
#
# Produces Resources/codec2.xcframework with slices:
#   macos-arm64_x86_64, ios-arm64, ios-simulator-arm64_x86_64
# Each slice carries libcodec2.a + the codec2 headers and a Clang modulemap that
# declares ONLY the `CCodec2` module. The opus module/headers live entirely in
# opus.xcframework (see build-opus.sh) — they are deliberately NOT bundled here.
# Bundling opus.h in both xcframeworks made a clean Xcode app build fail with
# "Multiple commands produce …/include/opus.h" (each binary target stages its
# public headers into the same products include dir). Keeping each xcframework
# self-contained avoids the collision. Finishes by zipping + printing the
# SwiftPM checksum.
#
# Usage:
#   bash scripts/build-codec2.sh           # clones the pinned codec2 + opus tags
#   CODEC2_SRC=/path OPUS_SRC=/path bash scripts/build-codec2.sh   # local checkouts
#
# Prereqs: Xcode + iOS SDK, cmake, git.

set -euo pipefail

CODEC2_VERSION="${CODEC2_VERSION:-1.2.0}"   # note: codec2 tags have no 'v' prefix
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_ROOT="${BUILD_ROOT:-/tmp/codec2_build}"
XCFW="$REPO_ROOT/Resources/codec2.xcframework"
NCPU="$(sysctl -n hw.logicalcpu)"

mkdir -p "$BUILD_ROOT"
# Resources/ is gitignored now that the binaries live in Releases, so it may not
# exist on a fresh checkout — create it before staging the xcframework + zip.
mkdir -p "$REPO_ROOT/Resources"

# --- source at pinned tag ---
if [ -n "${CODEC2_SRC:-}" ]; then SRC="$CODEC2_SRC"; else
    SRC="$BUILD_ROOT/codec2-$CODEC2_VERSION"
    [ -d "$SRC" ] || { echo "==> cloning codec2 $CODEC2_VERSION"; git clone --depth 1 --branch "$CODEC2_VERSION" https://github.com/drowe67/codec2 "$SRC"; }
fi
echo "==> codec2 source: $SRC"

build_slice() {            # name  extra-cmake-flags...
    local name="$1"; shift
    local dir="$BUILD_ROOT/$name"
    rm -rf "$dir"; mkdir -p "$dir"
    ( cd "$dir" && cmake "$SRC" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF "$@" >/dev/null \
        && cmake --build . --config Release --target codec2 -j"$NCPU" >/dev/null )
    echo "$dir/src/libcodec2.a"
}

IOS_SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
SIM_SDK="$(xcrun --sdk iphonesimulator --show-sdk-path)"

echo "==> building slices"
MAC_ARM=$(build_slice macos_arm64  -DCMAKE_OSX_ARCHITECTURES=arm64)
MAC_X86=$(build_slice macos_x86_64 -DCMAKE_OSX_ARCHITECTURES=x86_64)
IOS_ARM=$(build_slice ios_arm64    -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64  -DCMAKE_OSX_SYSROOT="$IOS_SDK")
SIM_ARM=$(build_slice sim_arm64    -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64  -DCMAKE_OSX_SYSROOT="$SIM_SDK")
SIM_X86=$(build_slice sim_x86_64   -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_OSX_SYSROOT="$SIM_SDK")

echo "==> lipo universal libs"
lipo -create "$MAC_ARM" "$MAC_X86" -output "$BUILD_ROOT/libcodec2_macos.a"
lipo -create "$SIM_ARM" "$SIM_X86" -output "$BUILD_ROOT/libcodec2_sim.a"

# --- assemble header dir (codec2 headers + CCodec2-only modulemap) ---
HDR="$BUILD_ROOT/codec2_headers"
rm -rf "$HDR"; mkdir -p "$HDR/codec2"
cp "$SRC/src/codec2.h" "$HDR/codec2.h"
# codec2/version.h is generated by cmake into the macOS-arm64 build tree.
VER="$(find "$BUILD_ROOT/macos_arm64" -path '*/codec2/version.h' -print -quit)"
[ -n "$VER" ] || { echo "error: generated codec2/version.h not found" >&2; exit 1; }
cp "$VER" "$HDR/codec2/version.h"
cat > "$HDR/module.modulemap" <<'MODMAP'
module CCodec2 {
    header "codec2.h"
    export *
}
MODMAP

echo "==> assembling xcframework"
rm -rf "$XCFW" "$BUILD_ROOT/codec2.xcframework"
xcodebuild -create-xcframework \
    -library "$BUILD_ROOT/libcodec2_macos.a" -headers "$HDR" \
    -library "$IOS_ARM"                       -headers "$HDR" \
    -library "$BUILD_ROOT/libcodec2_sim.a"    -headers "$HDR" \
    -output "$BUILD_ROOT/codec2.xcframework" >/dev/null
cp -R "$BUILD_ROOT/codec2.xcframework" "$XCFW"

echo "==> zip + checksum"
( cd "$REPO_ROOT/Resources" && rm -f codec2.xcframework.zip && zip -q -r -y codec2.xcframework.zip codec2.xcframework )
echo "==> codec2.xcframework.zip ready:"
swift package compute-checksum "$REPO_ROOT/Resources/codec2.xcframework.zip"
